//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OOADProject.Controllers
{
    using System;
    using System.Collections.Generic;
    
    public partial class SearchHistoryLog
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public string Keyword { get; set; }
        public string filter { get; set; }
        public System.DateTime Datetime { get; set; }
    
        public virtual User User { get; set; }
    }
}
